CREATE DATABASE IF NOT EXISTS morpher;

USE morpher;

CREATE TABLE IF NOT EXISTS `data` (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  counter int NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

INSERT INTO `data` (id, counter) VALUES(1, 0);

